### ISSUE TITLE
Charm sometimes gets into an error state when trying to check whether the pgBackRest TLS server is running in the primary

### ISSUE THREAD

**Issue by marceloneppel** [canonical/postgresql-operator#154]
## Steps to reproduce
1. Run the `backup-integration` tox environment.

## Expected behavior
The charm mustn't get into an error state.

## Actual behavior
The charm sometimes gets into an error state when trying to check whether the pgBackRest TLS server is running in the primary.

## Versions

Operating system: Ubuntu 22.04.2

Juju CLI: 2.9.42

Juju agent: 2.9.42

Charm revision: not published revision

LXD: 5.14-7072c7b

## Log output
https://github.com/canonical/postgresql-operator/actions/runs/5176724056/jobs/9326224369#step:6:193

## Additional context
It happens only sometimes.

**Comment by taurus-forever** [comment]
@marceloneppel should this be addressed in a87c52b03c91f824a439a9d11e276c667e4596eb ?

**Comment by marceloneppel** [comment]
> @marceloneppel should this be addressed in [a87c52b](https://github.com/canonical/postgresql-operator/commit/a87c52b03c91f824a439a9d11e276c667e4596eb) ?

I think it was. I checked all the CI runs on the main after those changes were merged, and none of them raised this issue.
