### ISSUE TITLE
Psql is missing from workload

### ISSUE THREAD

**Issue by kian99** [canonical/postgresql-operator#176]
## Steps to reproduce
Actions performed on local machine with lxd containers.
1. `juju deploy postgresql --channel=14/stable --revision=288`
2. `juju ssh postgresql/leader`
3. `psql`

`psql` not found.

## Expected behavior
Following the guide at https://charmhub.io/postgresql/docs/t-deploy-postgresql?channel=14/stable it was expected that psql would be installed on the machine. 

## Actual behavior
As above.

## Versions

Operating system: Ubuntu 22.04.2 LTS

Juju CLI: 2.9.43-ubuntu-amd64

Juju agent: 2.9.43

Charm revision: Machine charm 288 

Client version: 5.15
Server version: 5.15

## Additional context
The guide at https://charmhub.io/postgresql/docs/t-deploy-postgresql?channel=14/stable is also misleading, it initially states,
`juju run-action postgresql/leader get-password username=replication --wait`
but then suggests connecting with,
`psql --host=10.89.49.129 --username=operator --password --list`
Notice that the usernames are different.

I noticed this seems to be fixed on 14/edge

**Comment by taurus-forever** [comment]
Hi @kian99 ,

Thank you for reporting! The `psql` is available, but installed inside the SNAP. To call it use `charmed-postgresql.psql`.
The latest version of `14/edge` charm has SNAP alias created, see [PR1](https://github.com/canonical/postgresql-operator/pull/169) and [PR2](https://github.com/canonical/postgresql-operator/pull/170), the charm is more friendly now, just call `psql`!

Also the `14/stable` version has missing the following [fix](https://github.com/canonical/charmed-postgresql-snap/pull/13), so `charmed-postgresql.psql` cannot be used in `14/stable`.

Can you please check the version `14/edge` and report your findings there? Tnx!

**Comment by kian99** [comment]
Hi,

I can confirm the aliases worked as expected in 14/edge and realising it was a Snap inside the machine was interesting. Thanks for the info.
