### ISSUE TITLE
Machine Charm doesn't expose port 5432

### ISSUE THREAD

**Issue by kian99** [canonical/postgresql-operator#177]
## Steps to reproduce
1. `juju deploy postgresql --channel=14/edge`
2. `juju expose postgresql`
3. `juju status`

## Expected behavior
Expected the `Ports` heading under juju status to report port 5432/tcp was opened. Also expected `juju run --unit postgresql/0 opened-ports` to show port 5432. 

## Actual behavior
Instead no port is opened and in an Openstack deployment, the port 5432 is unreachable, i.e. `telnet <ip> 5432` is unable to connect. I was able to manually open the port by running `juju run --unit postgresql/0 open-port 5432/tcp`

Looking at the `ops` framework, I believe what is missing is the use of [open_port](https://ops.readthedocs.io/en/latest/#ops.Unit.open_port) somewhere in the charm code to inform Juju of which port to expose when `juju expose <app>` is used.

It's possible this applies to the k8s charm as well but I haven't tested that.

## Versions

Juju CLI: 2.9.42

Juju agent: 2.9.42

Charm revision: 14/edge revision 308

**Comment by dragomirp** [comment]
Hi, @kian99, expose should work now in edge (rev. 318)
