### ISSUE TITLE
The charm doesn't open-port when used in a CMR on openstack

### ISSUE THREAD

**Issue by nrobinaubertin** [canonical/postgresql-operator#197]
## Steps to reproduce

1. deploy postgresql rev312 on an openstack substrate
2. deploy another app (we used discourse-k8s edge) on another model
3. try to relate the two via a cross-model relation after exposing postgresql

## Expected behavior

discourse should be able to reach postgresql

## Actual behavior

discourse wasn't able to reach postgresql. We had to `juju run --unit postgresql/0 open-port 5432/tcp` to make it work. It seems that this operation is not made automatically in this case.

## Versions

Operating system: Ubuntu 20.04.6 LTS

Juju CLI: 2.9.44-ubuntu-amd64

Juju agent: 2.9.42

Charm revision: rev312

---

The fact that we should expose postgresql when doing a CMR is not stated in the doc either

**Comment by dragomirp** [comment]
Hi, Niels, we haven't implemented that yet ([DPE-1210](https://warthogs.atlassian.net/browse/DPE-1210)). We can try to prioritise it for the next pulse. Is it a major blocker for you?

**Comment by mthaddon** [comment]
@dragomirp we can work around it by running `juju run --unit ${unit-name} open-port 5432/tcp` but this bug just means anyone who's not aware of the workaround would be unable to use cross-model relations on openstack. I think getting it fixed in the next pulse would be fine.

**Comment by dragomirp** [comment]
Hi, @nrobinaubertin, latest edge (rev. 318) should be exposable. Sorry for the delay.
