### ISSUE TITLE
Cannot setup backups charm "cannot create user data directory"

### ISSUE THREAD

**Issue by kian99** [canonical/postgresql-operator#219]
## Steps to reproduce
This is running on Openstack attempting to setup backups following the instructions at https://charmhub.io/postgresql/docs/h-configure-s3-radosgw
1. Setup S3 bucket
2. juju deploy postgresql --channel=14/candidate --revision=307
3. juju deploy s3-integrator --config <bucket>=<bucket-name> ...
4. juju relate s3-integrator postgresql
5. juju run-action s3-integrator/leader sync-s3-credentials access-key=<access-key-here> secret-key=<secret-key-here> --wait

The action successfully runs and then the Postgres charm reports `failed to initialize stanza, check your S3 settings`
This seems to be different from #129 and #180 

## Expected behavior
Backups are configured.

## Actual behavior
Charm enters a blocked state as described above.

The output from `juju debug-log --replay --level WARNING` shows the following errors
```
unit-postgresql-2: 15:03:28 WARNING unit.postgresql/2.juju-log No relation: certificates
unit-postgresql-3: 15:06:44 ERROR unit.postgresql/3.juju-log s3-parameters:26: 2023/08/31 15:06:44.066373 cmd_run.go:1046: WARNING: cannot create user data directory: cannot create snap home dir: mkdir /nonexistent: permission denied
Sorry, home directories outside of /home needs configuration.
See https://forum.snapcraft.io/t/11209 for details.

unit-postgresql-2: 15:06:44 ERROR unit.postgresql/2.juju-log s3-parameters:26: 2023/08/31 15:06:44.568037 cmd_run.go:1046: WARNING: cannot create user data directory: cannot create snap home dir: mkdir /nonexistent: permission denied
Sorry, home directories outside of /home needs configuration.
See https://forum.snapcraft.io/t/11209 for details.

```

I can confirm the Postgres unit has network access to the s3 endpoint.

## Versions

Operating system: Ubuntu 22.04.3 LTS

Juju CLI: 2.9.44

Juju agent: 2.9.44

Charm revision: 307

LXD: N/A

## Log output
Juju debug log: See above 

Other relevant logs:
```
$ journalctl -u snap.charmed-postgresql.pgbackrest-service.service -n 8
Aug 31 09:42:16 juju-80e499-prod-product-attribution-db-8 charmed-postgresql.pgbackrest-service[14698]: ERROR: [037]: server command requires option: tls-server-auth
Aug 31 09:42:16 juju-80e499-prod-product-attribution-db-8 systemd[1]: snap.charmed-postgresql.pgbackrest-service.service: Main process exited, code=exited, status=37/n/a
Aug 31 09:42:16 juju-80e499-prod-product-attribution-db-8 systemd[1]: snap.charmed-postgresql.pgbackrest-service.service: Failed with result 'exit-code'.
Aug 31 09:42:16 juju-80e499-prod-product-attribution-db-8 systemd[1]: snap.charmed-postgresql.pgbackrest-service.service: Scheduled restart job, restart counter is at 5.
Aug 31 09:42:16 juju-80e499-prod-product-attribution-db-8 systemd[1]: Stopped Service for snap application charmed-postgresql.pgbackrest-service.
Aug 31 09:42:16 juju-80e499-prod-product-attribution-db-8 systemd[1]: snap.charmed-postgresql.pgbackrest-service.service: Start request repeated too quickly.
Aug 31 09:42:16 juju-80e499-prod-product-attribution-db-8 systemd[1]: snap.charmed-postgresql.pgbackrest-service.service: Failed with result 'exit-code'.
Aug 31 09:42:16 juju-80e499-prod-product-attribution-db-8 systemd[1]: Failed to start Service for snap application charmed-postgresql.pgbackrest-service.
```

**Comment by dragomirp** [comment]
Hi, @kian99, can you try to execute `charmed-postgresql.pgbackrest --config=/var/snap/charmed-postgresql/current/etc/pgbackrest/pgbackrest.conf info --output=json` within the VM as  the `snap_daemon`  user? That should give us more details. Also can you check where the home for `snap_daemon` is configured to be? From the logs, it seems to be set to `/nonexistent` while we expect it to be `/home/snap_daemon`.

**Comment by kian99** [comment]
Hi @dragomirp 
Seems I am unable to get into the `snap_daemon` user (probably because the the home directory is set to `/nonexistent`). I tried `sudo -i` to get into the root user then `su snap_daemon` but it puts me back into the shell for the root user, in contrast `su ubuntu` works.

Running the command from the ubuntu user
```
$ charmed-postgresql.pgbackrest --config=/var/snap/charmed-postgresql/current/etc/pgbackrest/pgbackrest.conf info --output=json
[]
```

And it looks a few users have their home directory set to `/nonexistent` strangely.
```
tcpdump:x:108:114::/nonexistent:/usr/sbin/nologin
snapd-range-524288-root:x:524288:524288::/nonexistent:/usr/bin/false
snap_daemon:x:584788:584788::/nonexistent:/usr/bin/false
```

What's odd is this was a clean instance that I deployed on openstack. There are 2 units of Postgres running and both have the same `/nonexistent` home folder for the snap_daemon. I will try to reproduce this again at some point and share if I manage to.

**Comment by dragomirp** [comment]
Hi, @kian99, I think https://github.com/canonical/postgresql-operator/pull/220 should reduce the chances of this happening on `edge`. On `candidate`, a workaround should be to wait for postgresql to active idle before relating with s3.

**Comment by kian99** [comment]
Ah I see, that makes sense. This was deployed with Terraform, so Postgres, s3-integrator and then relation would've all been deployed very close to each other.

I suppose the only fix currently is to teardown and redeploy? And make sure to wait for Postgresql to be active idle before relating.

**Comment by dragomirp** [comment]
> I suppose the only fix currently is to teardown and redeploy? And make sure to wait for Postgresql to be active idle before relating.

You can try manually running:
```
mkdir -p /home/snap_daemon
chown snap_daemon:snap_daemon /home/snap_daemon
usermod -d /home/snap_daemon snap_daemon
```
And rerelating with s3 to salvage the existing deployment.

**Comment by kian99** [comment]
Thank you, I managed to get it all working with that! Steps taken,
- On leader unit and replica the `/home/snap_daemon/` directory already existed
- `sudo chown snap_daemon:snap_daemon /home/snap_daemon`
- `sudo snap stop telegraf` (telegraf Snap was preventing the next command)
- `sudo usermod -d /home/snap_daemon snap_daemon`
- `sudo snap start telegraf`
- Repeat the above on replicate unit
- `juju relate postgresql s3-integrator` (integrator already setup)
- `juju run-action postgresql/leader list-backups --wait`
```
unit-postgresql-3:
  UnitId: postgresql/3
  id: "62"
  results:
    backups: |-
      backup-id             | backup-type  | backup-status
      ----------------------------------------------------
```
- `juju run-action postgresql/leader create-backup --wait`
```
unit-postgresql-3:
  UnitId: postgresql/3
  id: "64"
  results:
    backup-status: backup created
```
- `juju run-action postgresql/leader list-backups --wait`
```
unit-postgresql-3:
  UnitId: postgresql/3
  id: "66"
  results:
    backups: |-
      backup-id             | backup-type  | backup-status
      ----------------------------------------------------
      2023-09-04T08:43:39Z  | physical     | finished
```

Only one minor thing, `juju status` shows the replica unit still has a blocked status.
```
Unit                   Workload  Agent  Machine  Public address  Ports     Message
data-integrator/1*     active    idle   6           <ip>                   
postgresql/2           blocked   idle   7           <ip>         5432/tcp  failed to initialize stanza, check your S3 settings
  landscape-client/9*  active    idle               <ip>                   System successfully registered
  telegraf/9*          active    idle               <ip>         9103/tcp  Monitoring postgresql/2 (source version/commit d208a64)
  ubuntu-advantage/9*  active    idle               <ip>                   Attached (esm-apps,esm-infra,livepatch)
postgresql/3*          active    idle   8           <ip>          5432/tcp  Primary
  landscape-client/10  active    idle               <ip>                    System successfully registered
  telegraf/10          active    idle               <ip>          9103/tcp  Monitoring postgresql/3 (source version/commit d208a64)
  ubuntu-advantage/10  active    idle               <ip>                    Attached (esm-apps,esm-infra,livepatch)
s3-integrator/1*       active    idle   5           <ip>       
```

**Comment by dragomirp** [comment]
Hi, @kian99, there are some tweaks on latest edge (rev. 324) that should make this less likely to happen.
