### ISSUE TITLE
Add primary message in the primary unit

### ISSUE THREAD

**Issue by marceloneppel** [canonical/postgresql-operator#22]
Like in the k8s charm, it would be useful to have a `Primary` status message in the unit that is the primary.

One important details is that the message should be removed if the unit is not the primary anymore.

This shold also add a note like [this one](https://github.com/canonical/postgresql-k8s-operator/blob/62c636f7a957bfe234749b98df7516691959cbef/README.md?plain=1#L29) to the documentation.

**Comment by taurus-forever** [comment]
@marceloneppel IMHO this is no longer topical and works as described since 22.10 release.
