### ISSUE TITLE
Optionally change ownership on all tables in a DB when a relation is created

### ISSUE THREAD

**Issue by mthaddon** [canonical/postgresql-operator#247]
## Steps to reproduce

The discourse application has a requirement when running migrations that the user running the migrations owns all tables in the database.

Currently the postgresql charm adds "operator" permissions for the relation user, but doesn't change ownership on tables in the database. It would make redeployments of discourse (and potentially other applications that behave in a similar way) much smoother if there was an option to change ownership on all tables in a database.

1. Deploy postgresql charm
2. Create a database named discourse using a backup from another discourse instance
3. Add a relation from discourse-k8s to postgresql charm
4. See that it adds permissions to the database, but doesn't change ownership on tables
5. See an error in the discourse logs such as this:

```
ops.pebble.ExecError: non-zero exit code 1 executing ['/srv/discourse/app/bin/bundle', 'exec', 'rake', '--trace', 'db:migrate'], stdout='== 20210218144656 AddIsFavoriteToUserBadge: migrating =========================\n-- add_column(:user_b
adges, :is_favorite, :boolean)\n', stderr="** Invoke db:migrate (first_time)\n** Invoke db:load_config (first_time)\n** Invoke environment (first_time)\n** Execute environment\n** Execute db:load_config\n** Invoke environment \n** Invoke set_locale (first_time)\n** Execute set_loca
le\n** Execute db:migrate\nrake aborted!\nStandardError: An error has occurred, this and all later migrations canceled:\n\nPG::InsufficientPrivilege: ERROR:  must be owner of table user_badges\n/var/lib/gems/2.7.0/gems/rack-mini-profiler-2.3.3/lib/patches/db/pg.rb:110:in `exec'\n/v
```

## Expected behavior

There would be an option, possibly to `DatabaseRequires` to say you want all tables to be owned by the relation user.

## Actual behavior

As above

## Versions

Operating system: 14.04

Juju CLI: 3.1.6

Juju agent: 3.1.6

Charm revision: 

LXD: On openstack, but on any LXD version as well presumably

## Log output

See above

## Additional context

N/A

**Comment by marceloneppel** [comment]
Hi @mthaddon! Revision 349 has is on the `14/edge channel`. It should be promoted to `14/stable` soon.
