### ISSUE TITLE
Add an action for deleting backups

### ISSUE THREAD

**Issue by mthaddon** [canonical/postgresql-operator#257]
## Steps to reproduce

Currently removing older backups is quite a manual process involving connecting to the instance and invoking pgbackrest commands.

It would be nicer if we could use a juju action to delete backups in the same way that we can use an action to create and list backups.

e.g.:

```
$ juju run postgresql/0 list-backups
Running operation 13 with 1 task
  - task 14 on unit-postgresql-0

Waiting for task 14...
backups: |-
  backup-id             | backup-type  | backup-status
  ----------------------------------------------------
  2023-10-13T12:24:28Z  | physical     | finished

$ juju run postgresql/0 delete-backup --backup-id=2023-10-13T12:24:28Z
```

## Expected behavior

Being able to delete backups via an action

## Actual behavior

Have to manually delete backups using pgbackrest

## Versions

Operating system: 20.04

Juju CLI: 3.1.6

Juju agent: 3.1.6

Charm revision: 331

LXD: N/A, this is on OpenStack, but would apply on any LXD version as well.

**Comment by taurus-forever** [comment]
Dear Tom, please check it with Mohamed CC: @7annaba3l as it is a new feature.
The initial design was to use Managing storage lifecycle on public clouds (AWS, GCP)
https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lifecycle-mgmt.html

Unfortunately it is not an easy feature on S3 to implement it on background. :-(

**Comment by mthaddon** [comment]
I filed this bug after checking with @marceloneppel . The current process for deleting a backup is as follows (from a thread on public mattermost):

"""
For PG you need to do it through pgbackrest. You can SSH into the unit with `juju ssh --container postgresql postgresql-k8s/0 bash` (also on VM, you can ssh into it) and then you have two options to delete a backup.

Before deleting a backup, you need to get the name of the stanza with `pgbackrest info | head -n 1`. 

Then, as the first option, you can tell pgBackRest (the backup tool) to keep only a certain number of backups in the repository (it will remove the oldest ones):

```
pgbackrest --stanza=<name> --repo1-retention-full=<number of backups to keep> expire
# example: pgbackrest --stanza=test-backups-loyb.patroni-postgresql-k8s-aws --repo1-retention-full=3 expire
```

As a second option, you can delete a backup by providing a specific backup id (which is useful if you'd like to remove not the oldest backup, but one that was created later):

```
pgbackrest --stanza=<name> expire --set=<converted backup id>
# example: pgbackrest --stanza=test-backups-loyb.patroni-postgresql-k8s-aws expire --set=20230920-193335F
```

In the second option, you need to convert the backup id that is listed through `juju run-action postgresql-k8s/leader list-backups --wait` following some rules:

Remove hyphens and colons.
Replace T with -.
Replace Z with F.

2023-09-20T19:33:35Z becomes 20230920-193335F.

Those timestamps above are the same we have as the folder names.
"""
Either we need to script all of that and risk getting it wrong (and everyone else using the charm needs to do the same) or you could add an action doing it. If you're really unable to add an action for this before the feature to manage the entire storage lifecycle can you add some documentation of the above to the charm docs?

**Comment by marceloneppel** [comment]
The latest `14/stable` (rev. 429 for AMD64 and rev. 430 for ARM64) allows to define the backup retention: https://charmhub.io/postgresql/docs/h-manage-backup-retention?channel=14/stable.
