### ISSUE TITLE
Secure Patroni REST API from unauthorized access

### ISSUE THREAD

**Issue by marceloneppel** [canonical/postgresql-operator#27]
Secure the Patroni REST API to prevent misuse, like the commented example [here](https://github.com/canonical/postgresql-k8s-operator/pull/26#discussion_r955963163).

**Comment by taurus-forever** [comment]
@marceloneppel https://www.percona.com/blog/securing-patroni-rest-api-end-points-part-1/

**Comment by taurus-forever** [comment]
This issue will be addressed in https://warthogs.atlassian.net/browse/DPE-5269
