### ISSUE TITLE
Compression level default should not be 0

### ISSUE THREAD

**Issue by darkalia** [canonical/postgresql-operator#271]
## Steps to reproduce

1. Deploy postgresql charm
2. See the backup size on a big database

## Expected behavior
On a 200Gb database, something less than a 300GB backup.

## Actual behavior

For a 200GB database.
```
root@juju-32011b-prod-lists-canonical-com-6:/var/lib/postgresql/backups# ls -lah mailman3web.20231107_041301.dump
-rw------- 1 postgres postgres 309G Nov  7 04:42 mailman3web.20231107_041301.dump
```

## Versions

Charm revision:  latest/stable

## Additional context

Default backup should be compressed to some extent. Even a level 1 compression will improve greatly the experience

**Comment by darkalia** [comment]
That's actually the old charm.

I've created the relevant MP: https://code.launchpad.net/~ballot/postgresql-charm/+git/postgresql-charm/+merge/455250

**Comment by taurus-forever** [comment]
Dear @darkalia , thank you for the bugreport!

As you properly mentioned, it was a [legacy charm](https://charmhub.io/postgresql/docs/e-legacy-charm) behavior. 
The modern charm is using pgbackrest with gzip (level 6 compression, by default): https://pgbackrest.org/configuration.html#section-general/option-compress-type

Please reopen the ticket if it is still topical issue for modern charm. Tnx!
