### ISSUE TITLE
Replace hyphens with underscores in `profile-limit-memory` config option

### ISSUE THREAD

**Issue by marceloneppel** [canonical/postgresql-operator#303]
The `profile-limit-memory` (https://charmhub.io/postgresql/configure#profile-limit-memory) should use underscores instead of hyphens in its name to follow the pattern used by other config options.

Let's deprecate the current field and create a new one.

**Comment by taurus-forever** [comment]
Resolved as the fix is included in [revision 351](https://charmhub.io/postgresql/configure?channel=14/candidate#profile_limit_memory) (currently available in 14/candidate and will be released to 14/stable soon).
