### ISSUE TITLE
postgresql latest/stable 'update-status' hook updates pg_hba.conf in an infinite loop, overwriting local config

### ISSUE THREAD

**Issue by vorlonofportland** [canonical/postgresql-operator#324]
Have an environment that was initially deployed with the postgresql latest/stable charm around the end of Oct 2023.

Local modifications to pg_hba.conf were made to add a custom 'peer' map.

On December 8, 2023 there was a service outage because pg_hba.conf was overwritten out from under us, removing the custom entry.

An attempt was made to resolve this by adding the custom rule to 'juju config postgresql extra_pg_auth'; however, the juju charm adds the new line after 'local all all peer' and thus it is ineffective.

Have worked around this by running chattr +i on pg_hba.conf, leaving the charm in an error state.

## Expected behavior
* charm `update-status` hook does not repeatedly overwrite `pg_hba.conf`
* `extra_pg_auth` config is added above default rules, not below

## Actual behavior
* `extra_pg_auth` config is added after the line `local all all peer` making it inactive
* attempts to modify `pg_hba.conf` locally on the host are endlessly overwritten

## Versions

Operating system: Ubuntu 22.04.3 LTS (machine OS version: Ubuntu 20.04.6 LTS)

Juju CLI: 2.9.46-ubuntu-amd64

Juju agent: 2.9.44

Charm revision: 316

**Comment by dragomirp** [comment]
Hi, have you tried to set the custom hba changes in the Patroni config file? It should be located in `/var/snap/charmed-postgresql/current/etc/patroni`. You will most probably need to restart patroni for the changes to take effect.

**Comment by marceloneppel** [comment]
Hi @vorlonofportland! Thanks for the report. The charm you're using (from the `latest/stable` channel) is the legacy PostgreSQL charm maintained by the IS team.

The charm of this repository is published to the `14/stable` channel. However, it cannot add extra rules to the `pg_hba.conf` file.

As Dragomir said, you can use the `/var/snap/charmed-postgresql/current/etc/patroni` in this charm, but it will be overwritten in the next update status event.

You can also ask for our Product Manager, Mohamed Nsiri, in [our](https://matrix.to/#/#charmhub-data-platform:ubuntu.com) for that feature (something like `juju config postgresql extra_pg_auth`).

**Comment by vorlonofportland** [comment]
> Hi @vorlonofportland! Thanks for the report. The charm you're using (from the `latest/stable` channel) is the legacy PostgreSQL charm maintained by the IS team.

Yes, because this is the only version of the charm that works on focal due to the python venv bundling of binary extensions in the 14/stable version of the charm, so the 14/stable branch is useless to me.

charmhub.io does not list any separate bug filing information for different branches of this charm.  Since there is only one bug reporting link on charmhub.io, do you not have bug forwarding information for the IS-maintained branch?

**Comment by dragomirp** [comment]
Hi, @vorlonofportland, I don't think charmhub supports per branch details. I think the repository for the legacy charm is at https://launchpad.net/postgresql-charm or you can try to contact IS directly.

**Comment by dragomirp** [comment]
Doesn't look like we can help with anything. Closing the issue.
