### ISSUE TITLE
Tests stalling & hitting 2 hour limit

### ISSUE THREAD

**Issue by carlcsaposs-canonical** [canonical/postgresql-operator#339]
![Screenshot 2024-01-31 at 09-31-17 Allure Report](https://github.com/canonical/postgresql-operator/assets/115640263/3b1c6dc4-52f5-48c6-83ec-8a7fc1a0371a)
from https://canonical.github.io/postgresql-operator/1928/

Nightly tests runs have different # of executed tests because some tests are getting cancelled after hitting the 2 hour job timeout

e.g. https://github.com/canonical/postgresql-operator/actions/runs/7704852223/job/20998008804

**Comment by taurus-forever** [comment]
@carlcsaposs-canonical I think this is no longer topica, no tests above 1h50 mins now:https://canonical.github.io/postgresql-operator/2712/#graph

Still PG tests stability is a huge topic we are working on. Should we keep this open (as the mentioned subject is not topical anymore). Tnx!
