### ISSUE TITLE
Charm blocks legacy relation if it cannot connect to database

### ISSUE THREAD

**Issue by dragomirp** [canonical/postgresql-operator#352]
Updating the endpoints will [block](https://github.com/canonical/postgresql-operator/blob/main/src/relations/db.py#L294) the relation if it cannot connect and get the version of the database. I don't think we can clear the status. We should most probably retry the hook until connectivity recovers.

**Comment by marceloneppel** [comment]
Yeah, that blocked status is not being cleared. We should work on something like you commented on.

**Comment by taurus-forever** [comment]
@dragomirp the initial links points nowhere. Did we remove those blocking status?

**Comment by dragomirp** [comment]
> @dragomirp the initial links points nowhere. Did we remove those blocking status?

No, it's still here: https://github.com/canonical/postgresql-operator/blob/8c47bae588ba2c77c95a33f613a6d2ebe82197a9/src/relations/db.py#L322-L329

**Comment by dragomirp** [comment]
> IMHO, we should replace it to Error for now... and `juju resolve` will be a way to re-try when PG is up... WDYT?

I don't think we should be calling the DB here at all, we should get the version from the snap.

**Comment by taurus-forever** [comment]
Good point. Is it safe during the charm refresh? Snap is new on the first unit / but Primary DB is still old, etc.

**Comment by dragomirp** [comment]
Data is set (I'm not sure it's updated) per unit, so each unit should report its own PG version.
