### ISSUE TITLE
`memory_shared_buffers` config option does not work as expected

### ISSUE THREAD

**Issue by nishant-dash** [canonical/postgresql-operator#358]
## Steps to reproduce
Deploy a vm with 8GB RAM and postgresql charm  
```console
postgresql        14.9     active      3  postgresql        14/stable      351
```
then change the config
```sh
juju config postgresql memory_shared_buffers=256000
```

This is because i want about 2G to be allocated for the buffer (256000 * 8KB blocks)

## Expected behavior

For the charm to accept the change

## Actual behavior

```console
    raise Exception(
Exception: Shared buffers config option should be at most 40% of the available memory, which is 3328MB
```

## Versions

Operating system: 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"

Juju CLI: 2.9.46

Juju agent:  2.9.46

Charm revision: 351

LXD: N/A

## Log output

Juju debug log:  N/A

## Additional context

N/A

**Comment by marceloneppel** [comment]
https://github.com/canonical/postgresql-operator/pull/361 should fix this.

**Comment by dragomirp** [comment]
Latest 14/edge (rev. 370) should have the fix.
