### ISSUE TITLE
Test charm external storage deployment

### ISSUE THREAD

**Issue by BON4** [canonical/postgresql-operator#441]
# Smoke tests for deploying charm with external storage from another unit/application.

## Test cases
1. Removal Test. Install app, remove app, check no garbage left.
2. Re-installation test, install app 2nd time, remove with "-force --no-wait". Storage should be detached.
3. Unit garbage ignorance test. Deploy PostgreSQL unit with attached storage from another unit.
4. Application resources conflicts test. Deploy PostgreSQL application with attached storage from another application.

**Comment by marceloneppel** [comment]
Closed by https://github.com/canonical/postgresql-operator/pull/454.
