### ISSUE TITLE
Failed run integration tests with postgresql-test-app rev103

### ISSUE THREAD

**Issue by BalabaDmitri** [canonical/postgresql-operator#443]
## Steps to reproduce

1. tox -e integration

## Expected behavior
The integration tests finishes successfully.

## Actual behavior

When deploying, the default is the latest revision of `postgresql-test-app` (rev103), and then the tests fail.

## Versions

Operating system: Ubuntu 22.04.4 LTS

Juju CLI: 3.1.8-genericlinux-amd64

Juju agent: 3.1.7

Charm revision: postgresql-test-app=103

LXD: 5.21.1 LTS

## Additional context
If I substitute a specific revision for example 101, then the test passes successfully
I have reported the issue at [postgresql-test-app](https://github.com/canonical/postgresql-test-app/issues/119) repository

**Comment by taurus-forever** [comment]
I cannot reproduce this with the latest/stable postgresql-test-app. Please reopen if still topical. Tnx!
