### ISSUE TITLE
Permanent blocked status `Unsatisfied plugin dependencies. Please check the logs` after enabling the necessary plugins

### ISSUE THREAD

**Issue by taurus-forever** [canonical/postgresql-operator#466]
## Steps to reproduce
1. juju deploy postgresql # 14/stable rev 363
2. juju config -m landscape postgresql | grep plugin | tr -d ":" | xargs -i juju config postgresql {}=true # enable all plugins
Charm is blocked as expected: cannot enable address_standardizer, extension required postgis to be enabled before

3. juju config postgresql plugin_address_standardizer_enable=false
4. juju wait-for application postgresql
5. juju config postgresql plugin_address_standardizer_enable=true   

## Expected behavior
Charm is in active state as all extensions are enabled.

## Actual behavior
Charm stays blocked.

## Versions
Operating system: 22.04
Juju CLI: 3.1.8
Juju agent: 3.1.8
Charm revision: rev 363 from 14/stable
LXD: 5.0.3-d921d2e

## Log output
Nothing.

## Additional context

It would be great avoid blocking charm in the first place IF user enable all the necessary plugins together but in random/wrong order (like in this case).

**Comment by dragomirp** [comment]
Should be fixed in latest edge (revs. 406, 407)
