### ISSUE TITLE
Move resource download to pytest code

### ISSUE THREAD

**Issue by marceloneppel** [canonical/postgresql-operator#5]
Move the download process of the Patroni resource (and any other resource) to the pytest code and use the Charmhub API to get it.

**Comment by taurus-forever** [comment]
@marceloneppel AFAIK all bits are coming from snap nowadays. Is it still topical?
CC: @dragomirp do you recall bits outside of our control?

**Comment by dragomirp** [comment]
> @marceloneppel AFAIK all bits are coming from snap nowadays. Is it still topical? CC: @dragomirp do you recall bits outside of our control?

Patroni used to be a resource, but it's now in the snap. I don't think this is still topical.
