### ISSUE TITLE
 Postgresql charm fails to initialize (rev 429)

### ISSUE THREAD

**Issue by nobuto-m** [canonical/postgresql-operator#548]
The original issue was opened in a wrong place so posting the pointer here to start the investigation.
https://bugs.launchpad.net/postgresql-charm/+bug/2074017

> I am unable to get Postgresql (rev 429) to initialize when deploying the charm with juju. The issue shows up as postgresql units never finishing the "agent initializing" step in juju. In the debug-log, I see a complaint about the charm not being found on disk. Sometimes, I also get a message about a Sha256 length 0 being not valid. Please see the attached debug.log for one example.
> 
> This does not happen with older revisions of the charm, and the environment has wide-open network connectivity. Other charms initialize fine.
> 
> I am using PostgreSQL charm as part of a Landscape deployment. The bundle is attached. I did not have this issue with a previous charm revision (345).

**Comment by taurus-forever** [comment]
We will investigate this issue and will reply to the original place: https://bugs.launchpad.net/postgresql-charm/+bug/2074017
